# Generated by Django 6.0.3 on 2026-04-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('player', 'Player')], default='player', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('session_type', models.CharField(choices=[('practice', 'Practice'), ('friendly', 'Friendly'), ('match', 'Match')], default='practice', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not Going')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rsvps', to='scheduling.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='scheduling.trainingsession')),
            ],
            options={
                'ordering': ['player__name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'player'), name='unique_session_player_rsvp')],
            },
        ),
    ]
