# Generated by Django 6.0.3 on 2026-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_sessionvotepoll_sessionvoteoption_sessionvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('drills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='scheduling.trainingsession')),
            ],
            options={
                'ordering': ['session__starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalSessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='scheduling.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='scheduling.trainingsession')),
            ],
            options={
                'ordering': ['player__name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'player'), name='unique_session_player_note')],
            },
        ),
    ]
