# Generated by Django 6.0.3 on 2026-04-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_sessionplan_personalsessionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('session_updated', 'Session Updated'), ('general', 'General')], default='general', max_length=40)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.player')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
