# Generated by Django 6.0.3 on 2026-04-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('registration_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TryoutCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('converted', 'Converted')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tryout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='scheduling.tryoutsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
