# Generated by Django 6.0.3 on 2026-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_tryoutsession_tryoutcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('injured', 'Injured'), ('recovering', 'Recovering')], default='eligible', max_length=20),
        ),
    ]
