# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutsession',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
