# Generated by Django 6.0.3 on 2026-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_trainingsession_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='medical_certification_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
