# Generated by Django 6.0.3 on 2026-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0014_match_teamgoal_playermatchstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermatchstat",
            name="aces",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="assists",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="blocks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="most_recent_injury",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="returns",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
