# Generated by Django 4.2.30 on 2026-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_updated', 'Session Updated'), ('training_created', 'Training Session Created'), ('tryout_created', 'Tryout Created'), ('stats_added', 'Stats Added'), ('general', 'General')], default='general', max_length=40),
        ),
    ]
