# Generated by Django 6.0.3 on 2026-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0021_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(
                choices=[
                    ("coach", "Coach"),
                    ("league_system_handler", "League System Handler"),
                    ("player", "Player"),
                ],
                default="player",
                max_length=32,
            ),
        ),
    ]
