# Generated by Django 6.0.3 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0026_upcominggame_gameattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffteamassignment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
