# Generated by Django 6.0.3 on 2026-04-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0027_staffteamassignment_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="opponent_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opponent_matches",
                to="scheduling.team",
            ),
        ),
    ]
