# Generated by Django 6.0.3 on 2026-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0028_match_opponent_team_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="notify_league_handler",
            field=models.BooleanField(
                default=False,
                help_text="Also send this announcement to league system handler(s).",
            ),
        ),
    ]
