# Generated by Django 6.0.3 on 2026-04-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0029_announcement_notify_league_handler"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSubscriptionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_fee",
                        to="scheduling.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("period_month", models.PositiveSmallIntegerField()),
                ("period_year", models.PositiveSmallIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "Card"), ("cash", "Cash")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_payments",
                        to="scheduling.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_year", "-period_month", "player"],
                "unique_together": {("player", "period_month", "period_year")},
            },
        ),
    ]
