# Generated by Django 6.0.3 on 2026-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0030_teamsubscriptionfee_membershippayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="court_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="court_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="court_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
