# Generated by Django 6.0.3 on 2026-04-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0031_team_court_lat_team_court_lng_team_court_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="prefer_not_to_say",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="gender_category",
            field=models.CharField(
                choices=[("mens", "Men's"), ("womens", "Women's"), ("mixed", "Mixed")],
                default="mixed",
                max_length=10,
            ),
        ),
    ]
