# Generated by Django 6.0.3 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0032_player_gender_team_gender_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
