# Generated by Django 6.0.3 on 2026-04-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0033_alter_player_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="gender_category",
            field=models.CharField(
                choices=[("mens", "Men's"), ("womens", "Women's"), ("mixed", "Mixed")],
                default="mixed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="upcominggame",
            name="gender_category",
            field=models.CharField(
                choices=[("mens", "Men's"), ("womens", "Women's"), ("mixed", "Mixed")],
                default="mixed",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GameRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="scheduling.upcominggame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_roster_entries",
                        to="scheduling.player",
                    ),
                ),
            ],
            options={
                "ordering": ["player__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player"), name="unique_game_roster_entry"
                    )
                ],
            },
        ),
    ]
