# Generated by Django 6.0.3 on 2026-04-27 00:00

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0034_gender_and_game_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='received_chat_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sent_chat_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]