from django.urls import path

from . import views

app_name = 'scheduling'

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('chatting/', views.chatting_hub, name='chatting_hub'),
    path('chatting/messages/', views.chatting_messages, name='chatting_messages'),
    path('chatting/unread/', views.chatting_unread_status, name='chatting_unread_status'),
    path('ai-analytics/', views.ai_analytics_hub, name='ai_analytics_hub'),
    path('auth/signup/', views.signup, name='signup'),
    path('auth/login/', views.login_view, name='login'),
    path('auth/logout/', views.logout_view, name='logout'),
    path('auth/pending/', views.pending_approval, name='pending_approval'),
    path('player/home/', views.player_home, name='player_home'),
    path('player/messages/', views.player_messages, name='player_messages'),
    path('player/soreness/', views.log_player_soreness, name='log_player_soreness'),
    path('coach/home/', views.coach_home, name='coach_home'),
    path('league-handler/home/', views.league_system_handler_home, name='league_system_handler_home'),
    path('league-handler/teams/', views.league_handler_manage_teams, name='league_handler_manage_teams'),
    path('league-handler/admins/new/', views.create_club_admin, name='create_club_admin'),
    path('staff/home/', views.admin_home, name='admin_home'),
    path('staff/pending/', views.pending_members, name='pending_members'),
    path('staff/pending/<int:player_id>/approve/', views.approve_member, name='approve_member'),
    path('staff/pending/<int:player_id>/reject/', views.reject_member, name='reject_member'),
    path('sessions/new/', views.create_session, name='create_session'),
    path('sessions/next/', views.next_session, name='next_session'),
    path('sessions/calendar/', views.sessions_calendar, name='sessions_calendar'),
    path('sessions/<int:session_id>/', views.session_detail, name='session_detail'),
    path('sessions/<int:session_id>/edit/', views.edit_session, name='edit_session'),
    path('sessions/<int:session_id>/cancel/', views.cancel_session, name='cancel_session'),
    path('availability/new/', views.submit_availability, name='submit_availability'),
    path('availability/<int:availability_id>/', views.availability_detail, name='availability_detail'),
    path('coach/availability/', views.coach_availability_overview, name='coach_availability_overview'),
    path('polls/new/', views.create_vote_poll, name='create_vote_poll'),
    path('polls/', views.polls_list, name='polls_list'),
    path('polls/<int:poll_id>/', views.vote_poll_detail, name='vote_poll_detail'),
    path('sessions/<int:session_id>/plan/', views.edit_session_plan, name='edit_session_plan'),
    path('sessions/personal-note/', views.personal_notes_overview, name='personal_notes_overview'),
    path('sessions/<int:session_id>/personal-note/', views.personal_note, name='personal_note'),
    path('notifications/', views.notification_inbox, name='notification_inbox'),
    path('notifications/<int:notification_id>/delete/', views.delete_notification, name='delete_notification'),
    path('tryouts/', views.tryout_list, name='tryout_list'),
    path('player/tryouts/', views.player_tryout_list, name='player_tryout_list'),
    path(
        'player/tryouts/<int:tryout_session_id>/registration/',
        views.player_tryout_registration_toggle,
        name='player_tryout_registration_toggle',
    ),
    path('tryouts/new/', views.create_tryout_session, name='create_tryout_session'),
    path('tryouts/register/', views.register_tryout_candidate, name='register_tryout_candidate'),
    path('tryouts/<int:tryout_session_id>/', views.tryout_session_detail, name='tryout_session_detail'),
    path('tryouts/<int:tryout_session_id>/delete/', views.delete_tryout_session, name='delete_tryout_session'),
    path('candidates/<int:candidate_id>/', views.tryout_candidate_detail, name='tryout_candidate_detail'),
    path('candidates/<int:candidate_id>/convert/', views.convert_tryout_candidate, name='convert_tryout_candidate'),
    path('players/status/', views.player_status_list, name='player_status_list'),
    path('players/<int:player_id>/', views.manage_player_detail, name='manage_player_detail'),
    path('players/<int:player_id>/scouting-report/', views.player_scouting_report, name='player_scouting_report'),
    path('players/<int:player_id>/chat/', views.chat_with_player, name='chat_with_player'),
    path('players/<int:player_id>/support/', views.player_support, name='player_support'),
    path('players/eligible/', views.eligible_players, name='eligible_players'),
    path('coaches/', views.coach_list, name='coach_list'),
    path('coaches/<int:coach_id>/', views.manage_coach_detail, name='manage_coach_detail'),
    path('coaches/<int:coach_id>/chat/', views.chat_with_coach, name='chat_with_coach'),
    path('coaches/<int:coach_id>/support/', views.coach_support, name='coach_support'),
    path('players/<int:player_id>/update/', views.update_player_status, name='update_player_status'),
    path('players/<int:player_id>/activate/', views.activate_player, name='activate_player'),
    path('players/<int:player_id>/deactivate/', views.deactivate_player, name='deactivate_player'),
    path('coaches/<int:coach_id>/deactivate/', views.deactivate_coach, name='deactivate_coach'),
    path('coach/rsvps/', views.coach_rsvp_overview, name='coach_rsvp_overview'),
    path('team-stats/', views.team_stats_dashboard, name='team_stats'),
    path('team-stats/record-match/', views.record_match, name='record_match'),
    path('team-stats/match/<int:match_id>/player-stats/', views.record_player_stats, name='record_player_stats'),
    path('team-stats/add-goal/', views.add_team_goal, name='add_team_goal'),
    path('team-stats/player/<int:player_id>/', views.player_stats_detail, name='player_stats_detail'),
    # Upcoming Games
    path('upcoming-games/', views.upcoming_games, name='upcoming_games'),
    path('upcoming-games/<int:game_id>/attend/', views.set_game_attendance, name='set_game_attendance'),
    path('coach/games/<int:game_id>/roster/', views.coach_game_roster, name='coach_game_roster'),
    path('league-handler/upcoming-games/', views.league_handler_upcoming_games, name='league_handler_upcoming_games'),
    path('league-handler/admins/pending/', views.pending_admins, name='pending_admins'),
    path('league-handler/admins/<int:assignment_id>/approve/', views.approve_admin, name='approve_admin'),
    path('league-handler/admins/<int:assignment_id>/reject/', views.reject_admin, name='reject_admin'),
    path('notifications/popup-data/', views.notifications_popup_data, name='notifications_popup_data'),
    path('opponent-analysis/', views.opponent_analysis, name='opponent_analysis'),
    # Subscription / Membership payments
    path('player/subscription/', views.subscription_home, name='subscription_home'),
    path('player/subscription/pay/', views.pay_subscription, name='pay_subscription'),
    path('staff/subscription/fee/', views.set_team_fee, name='set_team_fee'),
    path('staff/subscription/overview/', views.subscription_overview, name='subscription_overview'),
    path('staff/subscription/cash-pending/', views.pending_cash_payments, name='pending_cash_payments'),
    path('staff/subscription/cash/<int:payment_id>/confirm/', views.confirm_cash_payment, name='confirm_cash_payment'),
    # Court location
    path('staff/court-location/', views.set_court_location, name='set_court_location'),
    path('player/court-map/', views.court_map, name='court_map'),
]
