from django.urls import path

from . import views

app_name = 'scheduling'

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('auth/signup/', views.signup, name='signup'),
    path('auth/login/', views.login_view, name='login'),
    path('auth/logout/', views.logout_view, name='logout'),
    path('player/home/', views.player_home, name='player_home'),
    path('player/messages/', views.player_messages, name='player_messages'),
    path('coach/home/', views.coach_home, name='coach_home'),
    path('staff/home/', views.admin_home, name='admin_home'),
    path('sessions/new/', views.create_session, name='create_session'),
    path('sessions/next/', views.next_session, name='next_session'),
    path('sessions/calendar/', views.sessions_calendar, name='sessions_calendar'),
    path('sessions/<int:session_id>/', views.session_detail, name='session_detail'),
    path('sessions/<int:session_id>/edit/', views.edit_session, name='edit_session'),
    path('sessions/<int:session_id>/cancel/', views.cancel_session, name='cancel_session'),
    path('availability/new/', views.submit_availability, name='submit_availability'),
    path('availability/<int:availability_id>/', views.availability_detail, name='availability_detail'),
    path('coach/availability/', views.coach_availability_overview, name='coach_availability_overview'),
    path('polls/new/', views.create_vote_poll, name='create_vote_poll'),
    path('polls/', views.polls_list, name='polls_list'),
    path('polls/<int:poll_id>/', views.vote_poll_detail, name='vote_poll_detail'),
    path('sessions/<int:session_id>/plan/', views.edit_session_plan, name='edit_session_plan'),
    path('sessions/personal-note/', views.personal_notes_overview, name='personal_notes_overview'),
    path('sessions/<int:session_id>/personal-note/', views.personal_note, name='personal_note'),
    path('notifications/', views.notification_inbox, name='notification_inbox'),
    path('notifications/<int:notification_id>/delete/', views.delete_notification, name='delete_notification'),
    path('tryouts/', views.tryout_list, name='tryout_list'),
    path('tryouts/new/', views.create_tryout_session, name='create_tryout_session'),
    path('tryouts/register/', views.register_tryout_candidate, name='register_tryout_candidate'),
    path('tryouts/<int:tryout_session_id>/', views.tryout_session_detail, name='tryout_session_detail'),
    path('candidates/<int:candidate_id>/', views.tryout_candidate_detail, name='tryout_candidate_detail'),
    path('candidates/<int:candidate_id>/convert/', views.convert_tryout_candidate, name='convert_tryout_candidate'),
    path('players/status/', views.player_status_list, name='player_status_list'),
    path('players/<int:player_id>/', views.manage_player_detail, name='manage_player_detail'),
    path('players/<int:player_id>/chat/', views.chat_with_player, name='chat_with_player'),
    path('players/<int:player_id>/support/', views.player_support, name='player_support'),
    path('players/eligible/', views.eligible_players, name='eligible_players'),
    path('coaches/', views.coach_list, name='coach_list'),
    path('coaches/<int:coach_id>/', views.manage_coach_detail, name='manage_coach_detail'),
    path('coaches/<int:coach_id>/chat/', views.chat_with_coach, name='chat_with_coach'),
    path('coaches/<int:coach_id>/support/', views.coach_support, name='coach_support'),
    path('players/<int:player_id>/update/', views.update_player_status, name='update_player_status'),
    path('players/<int:player_id>/deactivate/', views.deactivate_player, name='deactivate_player'),
    path('coaches/<int:coach_id>/deactivate/', views.deactivate_coach, name='deactivate_coach'),
    path('coach/rsvps/', views.coach_rsvp_overview, name='coach_rsvp_overview'),
]
